name: Check Event Database

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd python_tools && pip install
      - name: Checking database results...
        run: |
          cd python_tools && pipenv run python3 check_db.py