name: Check Event Database

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install Python, pipenv and Pipfile packages
        working-directory: ./python_tools
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./python_tools
        run: |
          python -m pip install --upgrade pip
          pipenv install
      - name: Checking database results...
        working-directory: ./python_tools
        run: |
          pipenv run python3 check_db.py